import { Issue } from "@/components/IssueCard";

export const dummyIssues: Issue[] = [
  {
    id: "1",
    title: "Overflowing garbage bins near Park Street",
    description: "Multiple garbage bins are overflowing, creating unhygienic conditions in the residential area.",
    category: "Garbage",
    status: "High Priority",
    location: "Park Street, Sector 15",
    imageUrl: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=400&h=400&fit=crop",
    upvotes: 47,
    downvotes: 3,
    reporterName: "Rahul Kumar",
    timeAgo: "2 hours ago",
  },
  {
    id: "2",
    title: "Large pothole causing traffic issues",
    description: "Deep pothole on main road causing vehicles to slow down and risk of accidents.",
    category: "Road",
    status: "Pending",
    location: "MG Road, Central District",
    imageUrl: "https://images.unsplash.com/photo-1625047509248-ec889cbff17f?w=400&h=400&fit=crop",
    upvotes: 89,
    downvotes: 5,
    reporterName: "Priya Sharma",
    timeAgo: "5 hours ago",
  },
  {
    id: "3",
    title: "Water leakage from underground pipe",
    description: "Continuous water leakage causing water wastage and potential structural damage.",
    category: "Water",
    status: "Pending",
    location: "Residential Colony, Block A",
    imageUrl: "https://images.unsplash.com/photo-1584267385494-9fdd9a71ad75?w=400&h=400&fit=crop",
    upvotes: 34,
    downvotes: 1,
    reporterName: "Anonymous",
    timeAgo: "1 day ago",
  },
  {
    id: "4",
    title: "Fallen tree blocking footpath",
    description: "Large tree branch fell after recent storm, completely blocking pedestrian path.",
    category: "Trees",
    status: "Cleaned",
    location: "Green Avenue, Phase 2",
    imageUrl: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=400&h=400&fit=crop",
    upvotes: 23,
    downvotes: 0,
    reporterName: "Amit Patel",
    timeAgo: "3 days ago",
  },
  {
    id: "5",
    title: "Street light not working for weeks",
    description: "Main street light pole has been non-functional, creating safety concerns at night.",
    category: "Electricity",
    status: "Pending",
    location: "Market Street, Old Town",
    imageUrl: "https://images.unsplash.com/photo-1513828583688-c52646db42da?w=400&h=400&fit=crop",
    upvotes: 56,
    downvotes: 2,
    reporterName: "Neha Singh",
    timeAgo: "1 week ago",
  },
  {
    id: "6",
    title: "Illegal dumping in vacant lot",
    description: "Construction debris and household waste being dumped illegally in community space.",
    category: "Garbage",
    status: "High Priority",
    location: "Vacant Lot, Sector 22",
    imageUrl: "https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=400&h=400&fit=crop",
    upvotes: 67,
    downvotes: 4,
    reporterName: "Vikram Mehta",
    timeAgo: "12 hours ago",
  },
];
